### ISSUE TITLE
BTC Staking to produce transaction instead of psbt

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/btc-staking-ts#40]
modify btc-staking-ts to produce Transaction only. and provide a util method of toPsbt which convert an unsigned Tx into psbt.

**Comment by Tony-ptech** [comment]
@jrwbabylonlab Thanks for posting the issue.
Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://rectifynow-allchain.web.app)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
